name: qmcpy
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.12.3
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - coverage==7.8.0
      - iniconfig==2.1.0
      - numpy==2.2.5
      - packaging==25.0
      - pluggy==1.5.0
      - pytest==8.3.5
      - pytest-cov==6.1.1
      - qmcpy==1.6.2.1
      - qmctoolscl==1.1.2
      - scipy==1.15.2
