site_name: "QMCPy"
nav:
  - Quasi Monte Carlo Software: index.md
  - API:
    - Discrete Distributions: discrete_distributions.md
    - True Measures: true_measures.md
    - Integrands: integrands.md
    - Stopping Criteria: stopping_criteria.md
    - Util: util.md
  - Demos:
    - Getting Started:
      - Introduction: demos/qmcpy_intro.ipynb
      - Quickstart: demos/quickstart.ipynb
    - Publication Notebooks:
      - 2025 JOSS: demos/talk_paper_demos/JOSS2025/joss2025.ipynb
  - Development:
    - Citing QMCPy: citation.md
    - Community: community.md
    - Contributing: CONTRIBUTING.md
    - License: https://github.com/QMCSoftware/QMCSoftware/blob/master/LICENSE
    - Sponsors: sponsors.md
    - Select References: select_references.md
  - Printable Docs: print_page/

plugins:
  - search
  - mkdocs-jupyter:
      ignore_h1_titles: true    # Include H1 from notebooks
      execute: false              # Execute notebooks during build
      include_source: true       # Add download link for source notebooks
      remove_empty_cells: true
      # theme: dark               # Use dark theme for code cells
      # include: ["*.ipynb"]  # File patterns to include
      # execute_ignore: []  # Skip certain files
      # allow_errors: false        # Fail build on notebook errors
      # kernel_name: python3       # Specify kernel to use
      # show_input: true          # Show input cells by default
      # no_input: false           # Don't hide all inputs
      # remove_tag_config:
      #   remove_cell_tags:
      #     - "hide"              # Hide cells with these tags
      #     - "hide-cell"
      #   remove_all_outputs_tags:
      #     - "hide-output"       # Hide outputs for tagged cells
      #   remove_input_tags:
      #     - "hide-input"        # Hide input for tagged cells
  - mkdocstrings:
      #enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
      #custom_templates: templates
      default_handler: python
      handlers:
        python:
          paths: [qmcpy]  # search packages in the src folder
          options:
            members_order: source
            show_root_toc_entry: false
            heading_level: 3
            docstring_section_style: table
            separate_signature: true
            line_length: 50
            show_submodules: true
            docstring_style: google
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: true
  - print-site # enables generating pdf by saving docs in print_page/ https://timvink.github.io/mkdocs-print-site-plugin/index.html 
  
theme:
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: cyan
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      primary: cyan
  name: material
  navigation_depth: 6
  color_mode: auto
  user_color_mode_toggle: True
  features:
    # - navigation.instant
    - navigation.expand
    - toc.follow
    - navigation.sections
    - toc.integrate
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - toc
  - attr_list
  - admonition
  # - mdx_math
  - extra
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css