name: QMCPy Automated Tests and Coverage Report
on: [push]

jobs:
  tests:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
            os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-activate-base: true
      - run: python -V
      - run: pip install -e .
      - run: pip install pytest 
      - run: pip install pytest-cov
      - run: make doctests_minimal
      - run: pip install -e .[torch] 
      - run: make doctests_torch 
      - run: pip install -e .[gpytorch]
      - run: make doctests_gpytorch
      - run: pip install -e .[botorch]
      - run: make doctests_botorch
      - run: pip install -e .[umbridge]
      - run: make doctests_umbridge
        if: '$RUNNER_OS" == "Linux"'
      - run: make unittests_fast
      - run: make unittests_slow
      - name: Update Coverage Badge # https://github.com/marketplace/actions/coverage-badge
        # GitHub actions: default branch variable
        # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
        if: ${{github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && '$RUNNER_OS" == "Linux"'}}
        uses: QMCSoftware/coverage-badge-action@main
